from flask import Flask, render_template, request, jsonify, session, redirect
import json
from datetime import datetime
from openai import OpenAI
import config
import re
from flask_mysqldb import MySQL

app = Flask(__name__)
app.config['SECRET_KEY'] = config.secret_key

client = OpenAI(api_key=config.api_key)

# 1 MySQL Configuration
import os

app.config['MYSQL_HOST'] = os.environ.get('MYSQL_HOST', 'localhost')
app.config['MYSQL_USER'] = os.environ.get('MYSQL_USER', 'root')
app.config['MYSQL_PASSWORD'] = os.environ.get('MYSQL_PASSWORD', '6827')
app.config['MYSQL_DB'] = os.environ.get('MYSQL_DB', 'ai_code_mentor')

mysql = MySQL(app)

# 2 Logging
def log_event(data):
    data["timestamp"] = str(datetime.now())
    with open("system_logs.json", "a") as f:
        f.write(json.dumps(data) + "\n")

# 3 Code Validation
def validate_code(code):
    if not code.strip():
        return False, "Code is empty."

    try:
        compile(code, "<string>", "exec")
    except Exception as e:
        return False, f"Syntax Error: {str(e)}"

    return True, "Valid"

# 4 Verdict
def get_verdict(code):

    prompt = f"""
You are a strict logical evaluator.

Analyze this Python code:

{code}

Respond EXACTLY in this format:

VERDICT: CORRECT or INCORRECT
CONFIDENCE: X%
"""

    response = client.chat.completions.create(
        model=config.model_name,
        temperature=0,
        messages=[{"role": "user", "content": prompt}]
    )

    text = response.choices[0].message.content

    verdict_match = re.search(r"VERDICT:\s*(CORRECT|INCORRECT)", text)
    confidence_match = re.search(r"CONFIDENCE:\s*(\d+)%", text)

    verdict = verdict_match.group(1) if verdict_match else "INCORRECT"
    confidence = int(confidence_match.group(1)) if confidence_match else 50

    return verdict, confidence

# 5 Time Complexity
def get_time_complexity(code):

    prompt = f"""
Analyze the following Python code:

{code}

Provide ONLY:

TIME COMPLEXITY:
O(...)
Short explanation.
"""

    response = client.chat.completions.create(
        model=config.model_name,
        temperature=0,
        messages=[{"role": "user", "content": prompt}]
    )

    return response.choices[0].message.content.strip()

# 6 Space Complexity
def get_space_complexity(code):

    prompt = f"""
Analyze the following Python code:

{code}

Provide ONLY:

SPACE COMPLEXITY:
O(...)
Short explanation.
"""

    response = client.chat.completions.create(
        model=config.model_name,
        temperature=0,
        messages=[{"role": "user", "content": prompt}]
    )

    return response.choices[0].message.content.strip()

# 7 Feedback
def get_feedback(code, verdict):

    if verdict == "CORRECT":

        prompt = f"""
You are a supportive coding mentor.

This code is logically correct:

{code}

Provide ONLY:

THINGS DONE WELL:
- Clear strengths.

LOGICAL ANALYSIS:
- Why it works.

FINAL SCORE:
X/10
Reason: short justification.

ENCOURAGEMENT:
- One motivating sentence.
"""

    else:

        prompt = f"""
You are a supportive coding mentor.

This code has logical issues:

{code}

Provide ONLY:

THINGS TO RETHINK:
- Weak areas.

CONCEPTS TO REVIEW:
- Relevant topics.

GUIDING QUESTIONS:
- Ask thinking-based questions.

FINAL SCORE:
X/10
Reason: short justification.

ENCOURAGEMENT:
- One motivating sentence.
"""

    response = client.chat.completions.create(
        model=config.model_name,
        temperature=config.temperature_review,
        messages=[{"role": "user", "content": prompt}]
    )

    return response.choices[0].message.content.strip()

# 8 AI Detection
def detect_ai_generated(code):

    prompt = f"""
Estimate the probability that the following Python code was generated by an AI.

Be conservative. Only give high probability if strongly confident.

Code:
{code}

Respond ONLY:
AI_PROBABILITY: X%
"""

    response = client.chat.completions.create(
        model=config.model_name,
        temperature=0,
        messages=[{"role": "user", "content": prompt}]
    )

    text = response.choices[0].message.content

    match = re.search(r'AI_PROBABILITY:\s*(\d+)%', text)
    gpt_prob = int(match.group(1)) if match else 50

    score = gpt_prob

    lines = code.strip().split("\n")

    if len(lines) <= 5:
        score -= 25

    if "input(" in code or "print(" in code:
        score -= 10

    if "#" in code:
        score -= 10

    if "  " in code:
        score -= 5

    if len(lines) > 15:
        score += 10

    if "temp" in code or "result" in code:
        score += 5

    
    final_score = max(0, min(100, score))

    if final_score >= 85:
        verdict = "AI"
    elif final_score >= 60:
        verdict = "UNCERTAIN"
    else:
        verdict = "HUMAN"

    return final_score, verdict

# 9 Home
@app.route("/")
def home():
    if "user_id" not in session:
        return redirect("/login")
    return render_template("index.html")

# 10 Review Route
@app.route("/review", methods=["POST"])
def review():

    if "user_id" not in session:
        return jsonify({"review": "Please login first."})

    code = request.form["code"]

    valid, message = validate_code(code)
    if not valid:
        return jsonify({"review": message})

    try:

        verdict, confidence = get_verdict(code)

        feedback = get_feedback(code, verdict)

        time_complexity = get_time_complexity(code) if verdict == "CORRECT" else None
        space_complexity = get_space_complexity(code) if verdict == "CORRECT" else None

        ai_probability, ai_verdict = detect_ai_generated(code)
        ai_flag = ai_probability >= 75

        cur = mysql.connection.cursor()

        error_count = 0 if verdict == "CORRECT" else 1

        cur.execute("""
        INSERT INTO submissions
        (user_id, goal, code, feedback, verdict, confidence, error_count, plagiarism_flag, plagiarism_probability)
        VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s)
        """,
        (
            session["user_id"],
            "N/A",
            code,
            feedback,
            verdict,
            confidence,
            error_count,
            ai_flag,
            ai_probability
        ))

        mysql.connection.commit()
        cur.close()

        log_event({
            "type": "review",
            "correctness": verdict,
            "confidence": confidence,
            "ai_probability": ai_probability
        })

        return jsonify({
            "feedback": feedback,
            "verdict": verdict,
            "confidence": confidence,
            "time_complexity": time_complexity,
            "space_complexity": space_complexity,
            "plagiarism_flag": ai_flag,
            "plagiarism_probability": ai_probability
        })

    except Exception as e:
        log_event({"type": "error", "error": str(e)})
        return jsonify({"review": "AI evaluation failed."})

# 11 Login
@app.route("/login", methods=["GET", "POST"])
def login():

    if request.method == "POST":

        email = request.form["email"]
        password = request.form["password"]

        cur = mysql.connection.cursor()

        cur.execute(
            "SELECT * FROM users WHERE email=%s AND password=%s",
            (email, password)
        )

        user = cur.fetchone()

        cur.close()

        if user:
            session["user_id"] = user[0]
            return redirect("/")

        else:
            return "Invalid credentials"

    return render_template("login.html")

# 12 Signup
@app.route("/signup", methods=["GET", "POST"])
def signup():

    if request.method == "POST":

        name = request.form["name"]
        email = request.form["email"]
        password = request.form["password"]

        cur = mysql.connection.cursor()

        cur.execute(
            "INSERT INTO users(name,email,password) VALUES(%s,%s,%s)",
            (name, email, password)
        )

        mysql.connection.commit()
        cur.close()

        return redirect("/login")

    return render_template("signup.html")

# 13 Profile
@app.route("/profile")
def profile():

    if "user_id" not in session:
        return redirect("/login")

    user_id = session["user_id"]

    cur = mysql.connection.cursor()

    cur.execute("SELECT name FROM users WHERE id=%s", (user_id,))
    user = cur.fetchone()

    cur.execute("""
    SELECT 
    COUNT(*) AS total_submissions,
    SUM(error_count) AS total_errors,
    SUM(plagiarism_flag) AS plagiarism_count
    FROM submissions
    WHERE user_id=%s
    """, (user_id,))
    
    stats = cur.fetchone()

    cur.execute("""
    SELECT verdict, confidence, plagiarism_flag, plagiarism_probability
    FROM submissions
    WHERE user_id=%s
    ORDER BY id DESC
    LIMIT 10
    """, (user_id,))
    
    history = cur.fetchall()

    cur.execute("""
    SELECT 
    u.name,
    SUM(s.error_count) AS errors,
    SUM(s.plagiarism_flag) AS plagiarism
    FROM users u
    JOIN submissions s ON u.id = s.user_id
    GROUP BY u.id
    ORDER BY plagiarism ASC, errors ASC
    LIMIT 5
    """)

    leaderboard = cur.fetchall()

    cur.close()

    return render_template(
        "profile.html",
        name=user[0],
        submissions=stats[0] or 0,
        errors=stats[1] or 0,
        plagiarism=stats[2] or 0,
        history=history,
        leaderboard=leaderboard
    )

# 14 Logout
@app.route("/logout")
def logout():
    session.clear()
    return redirect("/login")

# 15 Run
if __name__ == "__main__":
    app.run(debug=True)